INSERT IGNORE INTO warehouse (name, location) VALUES ('Warehouse1', 'New York');
INSERT IGNORE INTO warehouse (name, location) VALUES ('Warehouse2', 'Los Angeles');
INSERT IGNORE INTO warehouse (name, location) VALUES ('Warehouse3', 'Chicago');
INSERT IGNORE INTO warehouse (name, location) VALUES ('Warehouse4', 'San Diego');
INSERT IGNORE INTO warehouse (name, location) VALUES ('Warehouse5', 'Seattle');
INSERT IGNORE INTO warehouse (name, location) VALUES ('Warehouse6', 'Houston');
INSERT IGNORE INTO warehouse (name, location) VALUES ('Warehouse7', 'San Francisco');
INSERT IGNORE INTO warehouse (name, location) VALUES ('Warehouse8', 'Dallas');
INSERT IGNORE INTO warehouse (name, location) VALUES ('Warehouse9', 'Boston');
INSERT IGNORE INTO warehouse (name, location) VALUES ('Warehouse10', 'Miami');